logging:
  level:
    de.neuefische.passportpages: debug

spring:
  data:
    mongodb:
      database: passportPages

auth:
  jwt:
    secret: top-secret-for-token


oauth:
  github:
    client:
      id: Iv1.05ab67c0dfbf9e3c
      secret: 0ac30d0afed76224eab82ba9af833ae65c3bc1ca
    redirecturl: http://localhost:3000/oauth/github