name: Build and run backend tests

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with Maven
        env:
          AUTH_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          OAUTH_FACEBOOK_CLIENT_ID: ${{ secrets.FACEBOOK_CLIENT_ID }}
          OAUTH_FACEBOOK_CLIENT_SECRET: ${{ secrets.FACEBOOK_CLIENT_SECRET }}
          OAUTH_FACEBOOK_REDIRECT_URL: ${{ secrets.FACEBOOK_REDIRECT_URL }}
          OAUTH_GITHUB_CLIENT_ID: ${{ secrets.FANCY_CLIENT_ID }}
          OAUTH_GITHUB_CLIENT_SECRET: ${{ secrets.FANCY_CLIENT_SECRET }}
          OAUTH_GITHUB_REDIRECT_URL: ${{ secrets.FANCY_REDIRECT_URL }}
        run: mvn -B package --file ./pp-backend/pom.xml